replicaCount: 1

image:
  repository: ghcr.io/langfuse/langfuse
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

langfuse:
  nodeEnv: production
  nextauth:
    url:
      value: http://localhost:3000
      valueFrom: {}
    secret:
      value: changeme
      valueFrom: {}
  salt:
    value: changeme
    valueFrom: {}
  postgresql:
    host:
      value: ""
      valueFrom: {}
    auth:
      username:
        value: postgres
        valueFrom: {}
      password:
        value: postgres
        valueFrom: {}
      database:
        value: postgres_langfuse
        valueFrom: {}
    directURL:
      value: ""
      valueFrom: {}
    shadowDatabaseUrl:
      value: ""
      valueFrom: {}
  telemetryEnabled: True
  nextPublicSignUpDisabled: False
  enableExperimentalFeatures: False
  additionalEnv: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  auth:
    username: postgres
    password: postgres
    database: postgres_langfuse
  deploy: true
  architecture: standalone
  primary:
    service:
      ports:
        postgresql: 5432
