apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langfuse.fullname" . }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "langfuse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "langfuse.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "langfuse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: {{ .Values.langfuse.nodeEnv | quote }}
            - name: DATABASE_USERNAME
              valueFrom: {{ include "langfuse.postgresql.auth.username.valueFrom" . | nindent 16 }}
            - name: DATABASE_PASSWORD
              valueFrom: {{ include "langfuse.postgresql.auth.password.valueFrom" . | nindent 16 }}
            - name: DATABASE_HOST
              valueFrom: {{ include "langfuse.postgresql.databaseHost.valueFrom" . | nindent 16 }}
            - name: DATABASE_NAME
              valueFrom: {{ include "langfuse.postgresql.auth.database.valueFrom" . | nindent 16 }}
            {{- if not .Values.postgresql.deploy }}
            {{- if .Values.postgresql.directUrl }}
            - name: DIRECT_URL
              valueFrom: {{ include "langfuse.postgresql.directURL.valueFrom" . | nindent 16 }}
            {{- end }}
            {{- if .Values.postgresql.shadowDatabaseUrl }}
            - name: SHADOW_DATABASE_URL
              valueFrom: {{ include "langfuse.postgresql.shadowDatabaseURL.valueFrom" . | nindent 16 }}
            {{- end }}
            {{- end }}
            - name: NEXTAUTH_URL
              valueFrom: {{ include "langfuse.nextauth.url.valueFrom" . | nindent 16 }}
            - name: NEXTAUTH_SECRET
              valueFrom: {{ include "langfuse.nextauth.secret.valueFrom" . | nindent 16 }}
            - name: SALT
              valueFrom: {{ include "langfuse.salt.valueFrom" . | nindent 16 }}
            - name: TELEMETRY_ENABLED
              value: {{ .Values.langfuse.telemetryEnabled | quote }}
            - name: NEXT_PUBLIC_SIGN_UP_DISABLED
              value: {{ .Values.langfuse.nextPublicSignUpDisabled | quote }}
            - name: ENABLE_EXPERIMENTAL_FEATURES
              value: {{ .Values.langfuse.enableExperimentalFeatures | quote }}
            {{- range $key, $value := .Values.langfuse.additionalEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /api/public/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
